DROP DATABASE IF EXISTS `01`;
CREATE DATABASE `01`;

DROP TABLE IF EXISTS `01`.`ORDER`;
CREATE TABLE `01`.`ORDER`
(
    ID       INT AUTO_INCREMENT COMMENT '主键'
        PRIMARY KEY,
    DISTANCE VARCHAR(50) NOT NULL COMMENT '距离',
    STATUS   VARCHAR(50) NULL COMMENT '状态'
);

# 为用户授权
GRANT ALL PRIVILEGES ON `01`.* TO 'order'@'%';
FLUSH PRIVILEGES;
